#!/bin/sh
#
# fluxbox startup-script:
#
# Индикатор network manager
nm-applet &
# Не отключать монитор
xset s off
xset -dpms
# Установка раскладки клавиатуры
#setxkbmap -layout 'us,ru' -option 'grp:menu_toggle'
setxkbmap -layout 'us,ru' -option 'grp:ctrl_shift_toggle'
# Индикатор звука ALSA
#volumeicon &
# Яркость экрана xrandr монитор ViewSonic
#xrandr --output VGA1 --brightness 0.4
# Polkit-gnome add root access
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

exec fluxbox
